config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/search'
  root 'home#index'
  resources :shows do
    get :favorite
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :shows, :dependent => :destroy

  def self.channels_name
    ["Sony", "Colors", "Discovery", "Sabtv", "Zeetv", "Aajtak", "Indiatv"]
  end
  
  def self.random_time
    now = Time.now.to_i
    minute_ago = (Time.now - 60).to_i
    Time.at(rand(minute_ago..now))    
  end

  def self.random_show_name
    (0...8).map { (65 + rand(26)).chr }.join
  end
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :channel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shows = Show.all
  end

  def search
    query = params[:q]
    @channels = Channel.where('name LIKE ?', "%#{query}%")
    @shows = Show.where('name LIKE ?', "%#{query}%")
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:favorite]

  def favorite
    if params[:fav] == "true"
      @show.update(favorite: true)
    elsif
      @show.update(favorite: false)
    end
    redirect_to :root
  end

 private

 def set_show
   @show = Show.find(params[:show_id])
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/home/_search.html.erb
<%= form_with url: 'home/search', method: :get, local: true do |f| %>
  <%= f.label :q, "Search for:" %>
  <%= f.text_field :q, id: :q %>
  <%= f.submit "Search" %>
<% end %>

app/views/home/index.html.erb
<%= render "search" %> <br>

<table border="1">
		<tr>
			<td><b>Show Name</b></td>
			<td><b>Show Time</b></td>
			<td><b>Channel</b></td>
			<td><b>Action</b></td>
		</tr>
<% @shows.each do |show| %>
	<tr>
		<td><h2><%= show.name %></h2></td>
		<td><%= show.show_time %></td>
		<td><%= show.channel.name %></td>
		<% if show.favorite == false %>
		  <td><%= link_to "Mark Favorite", show_favorite_path(show, fav: true) %></td>
		<% else %>
		  <td><%= link_to "Remove Favorite", show_favorite_path(show) %></td>
		<% end %>  
	</tr>
<% end %>
</table>

app/views/home/search.html.erb
<h2>Search Result</h2>

<h3>Channels</h3>
<% @channels.each do |channel| %>
   <%= channel.name %> <br>
<% end %>

<h3>Shows</h3>
<% @shows.each do |show| %>
	<%= show.name %> <br>
<% end %>

<h1><%= link_to "Back To Home Page", root_url %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tvshow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>